server:

  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/micro_user_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-66014205.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oaaus6pj316mZ2PO5d7
            client-secret: N__X8VR7a7lvnZZWVdC-4o_VW4VmYy958ZbLzGxR_sJR2i7wkBMm8frpPLMHr5le

        provider:
          okta:
            issuer-uri: https://dev-66014205.okta.com/oauth2/default
  

spring.application.name: USER-SERVICE

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5000
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        
retry: 
  instances:
    ratingHotelService:
      max-attempts: 4
      wait-duration: 5000
      
okta:
  oauth2:
    issuer: https://dev-66014205.okta.com/oauth2/default
    audience: api://default
    